# ---- Estágio 1: builder ----

FROM python:3.13-slim AS builder

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir --target=/app/deps -r requirements.txt

# ---- Estágio 2: final ----
FROM python:3.13-slim

WORKDIR /app

COPY --from=builder /app/deps /app/deps
COPY main.py .

ENV PYTHONPATH=/app/deps

RUN useradd --create-home appuser
USER appuser

EXPOSE 8000

CMD ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
