name: Terraform CI

on:
  push:
    branches:
      - main
    paths:
      - "terraform-labs/03-remote-state/app/**"
      - ".github/workflows/terraform-ci.yml"

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: Terraform - remote state app
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform-labs/03-remote-state/app

    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v7

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.15.8"

      - name: Verificar formatacao
        run: terraform fmt -check -diff

      - name: Autenticar na AWS
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          role-to-assume: arn:aws:iam::910093226300:role/github-actions-terraform-ci
          aws-region: us-east-1

      - name: Verificar identidade AWS
        run: aws sts get-caller-identity
      
      - name: Inicializar Terraform
        run: terraform init -input=false -no-color

      - name: Validar Terraform
        run: terraform validate -no-color

      - name: Planejar Terraform
        run: terraform plan -input=false -no-color -lock-timeout=60s